### ISSUE TITLE
How to use function in query with .where()?

### ISSUE THREAD

**Issue by SlowburnAZ** [redexp/simple-object-query#1]
@redexp 

Hello,

Very useful library!  I've run into a problem I can't seem to solve, though...

My issue is how to use .where() to query for a property that has an array for a value.  For example:

`
var data = [{
    'item1': 'test1', 
    'item2': [
        'foo', 
        'bar'
    ]
},
{
    'item1': 'test2',
    'item2': [
        'foo1',
        'bar1'
    ]
}];
`

How would one go about using .where() to get only the objects where the 'item2' array contains 'foo1'?

I would assume you'd have to use a function to do so, but it's not clear from the documentation how you would do so.

Any help would be appreciated!

**Comment by redexp** [comment]
```javascript
var res = q.where(data, {
    'item1.item2': function (arr) {
        return arr.indexOf('foo') > -1;
    }
});
```
I should add this to example to docs
